version: '3'

volumes:
  minio-data:
    driver: local

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'backend'
    depends_on:
      - minio
    env_file:
      - .env
    ports:
      - "8083:8083"
    restart: on-failure


  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server --address :9000 ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio